import React from "react";

const Quotes =[
"'The mind is not a vessel to be filled but a fire to be ignited'. Plutarch",
"'Dont let what you cannot do interfere with what you can do'. John Wooden",
"'A person who never made a mistake never tried anything new.' — Albert Einstein",
"'Try not to become a man of success. Rather become a man of value.' —Albert Einstein",
"'Excellence is not a skill. It is an attitude.' —Ralph Marston",
"'Rule no.1 is: Don't sweat the small stuff. Rule no. 2 is:  It's all small stuff.' —Robert Eliot",
"'Quality is not an act, it is a habit.' —Aristotle",
"'I think it's possible for ordinary people to choose to be extraordinary.' — Elon Musk",
"'The best way to predict your future is to create it.' —Abraham Lincoln",
"'The future belongs to those who believe in the beauty of their dreams.' ― Eleanor Roosevelt",
"'Do the best you can until you know better. Then when you know better, do better.' —Maya Angelou",
"'Doubt kills more dreams than failure ever will.' —Karim Seddiki",
"'You are braver than you believe, stronger than you seem and smarter than you think.' — A.A Milne",
"'Go confidently in the direction of your dreams. Live the life you have imagined.' —Henry David Thoreau",
"'Learn from yesterday. Live for today. Hope for tomorrow.' Albert Einstein",
"'Today a reader. Tomorrow a leader.' Anonymous",
"'In a world where you can be anything, be kind.' — Jennifer Dukes Lee",
"'I don't love studying. I hate studying. I like learning. Learning is beautiful.'  Natalie Portman",
"'Work gives you meaning and purpose and life is empty without it.'  Stephen Hawking",
"'You can't have a better tomorrow if you're still thinking about yesterday.'  Charles F. Kettering",
"'The whole purpose of education is to turn mirrors into windows.'  Sydney J. Harris",
"'The purpose of our lives is to be happy.'  Dalai Lama",
"'Education is the most powerful weapon, which you can use to change the world.' —Nelson Mandela",
"'It always seems impossible until it's done.' — Nelson Mandela",
"'Study the past if you want to intuit the future.'  Confucius",
"'You can always be better.'  Tiger Woods",
"'There are far, far better things ahead than any we leave behind.' C.S. Lewis",
"'Hardships often prepare ordinary people for an extraordinary destiny.' —C.S. Lewis",
"'A dream you dream alone is only a dream. A dream you dream together is reality.' —Yoko Ono",
"'Striving for success without hard work is like trying to harvest where you haven't planted.  David Bly",
"'There is no elevator to success. You have to take the stairs.'  Zig Ziglar",
"'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.'  David Brinkley",
"'Great things are done by a series of small things brought together.' —Vincent van Gogh",
]

export default Quotes;